language: cpp

os:
  - linux

branches:
  only:
    - develop
    - master
    - testing
    - feature/*
    
sudo: 
    required

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         lsb_release -a
      && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt542
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 libc6-i386 qt54tools qt54svg qt54webkit qt54script
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      ;
    else
         brew update > /dev/null
      && brew install qt5
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi
    
script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         QTDIR="/opt/qt54"
      && PATH="$QTDIR/bin:$PATH"
      && qt54-env.sh 
      ;
    else
         QTDIR="/usr/local/opt/qt5"
      && PATH="$QTDIR/bin:$PATH"
      && LDFLAGS=-L$QTDIR/lib
      && CPPFLAGS=-I$QTDIR/include
      ;
    fi
  - cd ./whole_src
  - mkdir -p  build/tests
  - cd ./build/tests/
  - qmake ./../../project/qccex-alter_tests.pro && make -s -j 2
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      if [ "${TRAVIS_BRANCH}" != "master" ]; then
           ./../build/tests/qccex-alter_tests -platform minimal -txt
        ;
      fi
      ;
    else
         ./../bin/tests/tests.app/Contents/MacOS/tests -platform minimal -txt
      ;
    fi    
  - cd ../..
  - mkdir -p  build/release
  - cd ./build/release/
#  - echo "#define BUILD ""$TRAVIS_BUILD_NUMBER" > build_number.h
#  - echo "#define RELEASE \"Travis CI\"" > release.h
#  - echo CONFIG is $CONFIG
  - qmake ./../../project/qccex-alter.pro #CONFIG+=$CONFIG
  - make
  
before_deploy:
  - export VERSION_NUMBER=`1.0.6`
  # create debian package for linux and a disk image for OSX
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         cd ../../../travis
      && dpkg-deb -x qccex-alter.deb build 
      && mv build/opt/QOwnNotes/ build/opt/qccex-alter/
      && mv ../whole_src/build/release/qccex-alter build/opt/qccex-alter/
      && dpkg -b build qccex-alter333.deb
      ;
    else
         ../travis/create-dmg.sh
      ;
    fi
  #
  # add a tag
  #
  - TIME_STRING=`date +%H%M%S`
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         export GIT_TAG=linux-b$TRAVIS_BUILD_NUMBER-$TIME_STRING
      ;
    else
         export GIT_TAG=macosx-b$TRAVIS_BUILD_NUMBER-$TIME_STRING
      ;
    fi
#  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
#  - echo TAGPERM is $TAGPERM
#  - echo GIT_TAG is $GIT_TAG
#  - echo TRAVIS_BUILD_NUMBER is $TRAVIS_BUILD_NUMBER
#  - echo TIME_STRING is $TIME_STRING
#  - git push -q https://$TAGPERM@github.com/ValeriusGC/qccex-alter --tags

deploy:
  - provider: releases
   api_key: 
        secure: d70a10ae48da549a099f6d3e4e647877f7a11a8f
#    api_key:
#        secure: EyOMTm+fzo7rWhRMfROH8/jeJnSFmLFz4pfD/HuFJI2ohayHJOIfASMdg0d7N2cGFS9G7iuPUmQ1S56YC8BSnEefc3lASB1i5hiSOMWJV+lO3N1JBFCWxCBzHc9Hs+XKwHwyhZ5iIYncx+JHPYRNWtUD+A6SZHiZ+sVI48gYMyA=
    file: qccex-alter333.deb
    skip_cleanup: true
    on:
        repo: ValeriusGC/qccex-alter
        branch: master
        tags: false
        condition: ${TRAVIS_OS_NAME} = linux
#        condition: $CONFIG = release && ${TRAVIS_OS_NAME} = linux

notifications:
  recipients:
    - frostyland@gmail.com
  email:
    on_success: change
    on_failure: change
