language: cpp

os:
  - linux

branches:
  only:
    - develop
    - master
    - testing
    - feature/*
    
sudo: 
    required

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         lsb_release -a
      && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt542
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 libc6-i386 qt54tools qt54svg qt54webkit qt54script
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      ;
    else
         brew update > /dev/null
      && brew install qt5
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi
    
script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         QTDIR="/opt/qt54"
      && PATH="$QTDIR/bin:$PATH"
      && qt54-env.sh 
      ;
    else
         QTDIR="/usr/local/opt/qt5"
      && PATH="$QTDIR/bin:$PATH"
      && LDFLAGS=-L$QTDIR/lib
      && CPPFLAGS=-I$QTDIR/include
      ;
    fi
  - cd ./whole_src
  - mkdir -p  build/tests
  - cd ./build/tests/
  - qmake ./../../project/qccex-alter_tests.pro && make -s -j 2
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      if [ "${TRAVIS_BRANCH}" != "master" ]; then
           ./../build/tests/qccex-alter_tests -platform minimal -txt
        ;
      fi
      ;
    else
         ./../bin/tests/tests.app/Contents/MacOS/tests -platform minimal -txt
      ;
    fi    
  - cd ../..
  - mkdir -p  build/release
  - cd ./build/release/
#  - echo "#define BUILD ""$TRAVIS_BUILD_NUMBER" > build_number.h
#  - echo "#define RELEASE \"Travis CI\"" > release.h
#  - echo CONFIG is $CONFIG
  - qmake ./../../project/qccex-alter.pro #CONFIG+=$CONFIG
  - make
  
before_deploy:
  # 16/04/09 new 1.0.8 version
  - export VERSION_NUMBER=`1.0.8`
  # create debian package for linux and a disk image for OSX
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         cd ../../../travis
      && dpkg-deb -x qccex-alter.deb build 
      && mv ../whole_src/build/release/qccex-alter build/opt/qccex-alter/
      && dpkg -b build qccex-alter333.deb
      ;
    else
         ../travis/create-dmg.sh
      ;
    fi
  #
  # add a tag
  #
  - TIME_STRING=`date +%H%M%S`
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         export GIT_TAG=linux-b$TRAVIS_BUILD_NUMBER-$TIME_STRING
      ;
    else
         export GIT_TAG=macosx-b$TRAVIS_BUILD_NUMBER-$TIME_STRING
      ;
    fi
#  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
#  - echo TAGPERM is $TAGPERM
#  - echo GIT_TAG is $GIT_TAG
#  - echo TRAVIS_BUILD_NUMBER is $TRAVIS_BUILD_NUMBER
#  - echo TIME_STRING is $TIME_STRING
#  - git push -q https://$TAGPERM@github.com/ValeriusGC/qccex-alter --tags

deploy:
  - provider: releases
    api_key: 
        secure: JuD02QSDCFnba3RI/XtYmj8i3oWwlH+i6bGmOpeWdHrk3qagkDutJZGD74Th0dWH5+sbD/1/UP3tYf1Gs5nQZZoxdkFEI1Jm18DCcpSKM0YCkJjzW0c14vnNiYuds2OJvKFZIQki5nCRLL07Lj9xOzNmDkmazioine2yIBH5aWY6Xl3u3GyV2OjAwqIbYIXenv6njncmMUqeszooBgmYHIpGNM1buul23wAYaRNGwcG1T+j4n5vjJSeRWoAAcFo/awqvP2p6t8KhS2H4SwH1pRza505qhUeB8lN7gy7SuUpbf6jg/iqqv9v17EufJjw7pUwyT2xfkgI/vwM3ABR9m3EvwSCdioQEpihRChZynAKApsrp6uQ3agzOt39AUslccXocupNBFHu5Wosu3ReoxLOi35XOCIAWLWON+9xL3rliyfb9p2pYhxVLSi90qLqnOWDrdYW3pvmhbRYWABXn2Qf7p9tpD/Vm4UnTxflnufMYZUKoIM804BGn/xGBU9lnH57Q9iZxA2z6ZH34I4LuNJQ0MiKQbTBobvtCudgyRCSoNhHGf3Bid+D31kWlurc5B47G8puHuogob+v7R1z8AaapgOKLS93xBrLbt8YLFwJ08r8O65+98rGRzA5L5is8c2ZAz2uH/7Gz1V5IInjlxiekU8r+EeIS/Vd4HC2Y1Gg=
    file: qccex-alter333.deb
    skip_cleanup: true
    on:
        repo: ValeriusGC/qccex-alter
        branch: master
        tags: false
        condition: ${TRAVIS_OS_NAME} = linux
#        condition: $CONFIG = release && ${TRAVIS_OS_NAME} = linux

notifications:
  recipients:
    - frostyland@gmail.com
  email:
    on_success: change
    on_failure: change
